### ISSUE TITLE
error: name 'response' isn't defined

### ISSUE THREAD

**Issue by ndj-pi** [duckida/picow-lightswitches#1]
I tried running the one servo program but i got this error when i tried to connect on my pc. can you help me?
  Connection successful!
  IP address: ------------
  Setting up server
  Client connected
  Client connected
  Request: b'GET / HTTP/1.1\r\n'
  Request: /
  Task exception wasn't retrieved
  future: <Task> coro= <generator object 'handle_client' at 2001b5c0>
  Traceback (most recent call last):
    File "asyncio/core.py", line 1, in run_until_complete
    File "<stdin>", line 90, in handle_client
  NameError: name 'response' isn't defined

**Comment by duckida** [comment]
Try the other code for that type of switch.

**Comment by ndj-pi** [comment]
can it be used via a web page or does it have to be used with home assistant?

**Comment by duckida** [comment]
It is for Home Assistant, however it can be modified to add a web server.

**Comment by ndj-pi** [comment]
That would make sense.
I will let you know if I can get it working on home assistant and then I might mod the code to create a web server friendly version.
